spring.application.name=ApexRateLimiter

#spring.security.user.name=vijay
#spring.security.user.password=fiserv2022


server.max-http-request-header-size=16KB

trusted.client.serviceA.secret=superSecretKeyForServiceA123


# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Change the base path (default is /actuator)
management.endpoints.web.base-path=/actuator

# Optional: show health details
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.factory.realtime.realtime.controller=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG

server.error.whitelabel.enabled=false
# Show exactly why the JSON mapping failed
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# This will include the specific error message in the API response
server.error.include-message=always

# 1. Shows exactly which URL patterns are being matched/rejected
logging.level.org.springframework.security=DEBUG

# 3. Prints the full filter chain to your console on startup
spring.websecurity.debug=true

# 4. Optional: Shows why your JSON/Path variables might be failing
logging.level.org.hibernate=DEBUG


