spring.application.name=ExternalAPI

server.port=8090
# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Change the base path (default is /actuator)
management.endpoints.web.base-path=/actuator

# Optional: show health details
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.factory.realtime.realtime.controller=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG

server.error.whitelabel.enabled=false
# Show exactly why the JSON mapping failed
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# This will include the specific error message in the API response
server.error.include-message=always


